name: Test Helm Chart
on: 
  - push

jobs:
  k8s-test:
    runs-on: ubuntu-22.04
    steps:
      # GitHub Action reference: https://github.com/jupyterhub/action-k3s-helm
      - name: Kubernetes
        uses: jupyterhub/action-k3s-helm@6389a7f2a11343ea6b469628c6e7b3afa961db24 # v4
        with:
          # See available:
          # - k3s release channels at https://github.com/k3s-io/k3s/blob/HEAD/channel.yaml
          # - k3s versions at https://github.com/k3s-io/k3s/tags
          # - helm versions at https://github.com/helm/helm/tags
          k3s-version: v1.27.5+k3s1
          helm-version: v3.11.2
          metrics-enabled: false
          traefik-enabled: false

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Linting
        run: make lint

      - name: Install
        env:
          KUBE_LINTER_VER: 0.6.4
          KUBE_SCORE_VER: 1.17.0
          POLARIS_VER: 8.5.1
          KUBECONFORM_VER: 0.6.3
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yqq yamllint wget
          cd /tmp
          wget -q https://github.com/stackrox/kube-linter/releases/download/v${KUBE_LINTER_VER}/kube-linter-linux && sudo mv kube-linter-linux /usr/local/bin/kube-linter && sudo chmod +x /usr/local/bin/kube-linter
          wget -q https://github.com/zegl/kube-score/releases/download/v${KUBE_SCORE_VER}/kube-score_${KUBE_SCORE_VER}_linux_amd64 && sudo mv kube-score_${KUBE_SCORE_VER}_linux_amd64 /usr/local/bin/kube-score && sudo chmod +x /usr/local/bin/kube-score
          wget -q https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz && tar xf kubeval-linux-amd64.tar.gz && sudo mv kubeval /usr/local/bin && sudo chmod +x /usr/local/bin/kubeval
          wget -q https://github.com/FairwindsOps/polaris/releases/download/${POLARIS_VER}/polaris_linux_amd64.tar.gz && tar xf polaris_linux_amd64.tar.gz && sudo mv polaris /usr/local/bin && sudo chmod +x /usr/local/bin/polaris
          wget -q https://github.com/yannh/kubeconform/releases/download/v${KUBECONFORM_VER}/kubeconform-linux-amd64.tar.gz && tar xf kubeconform-linux-amd64.tar.gz && sudo mv kubeconform /usr/local/bin && sudo chmod +x /usr/local/bin/kubeconform
          helm plugin install https://github.com/helm-unittest/helm-unittest.git
        
      - name: Verify
        run: |
          yamllint --version
          kubeval --version
          kube-linter version
          kube-score version
          polaris version
          kubeconform -v
                  
      - name: Helm install
        run: |
          echo "kubeconfig: $KUBECONFIG"
          kubectl version
          kubectl get nodes
          kubectl get pods --all-namespaces
          helm version
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install external-secrets external-secrets/external-secrets --version 0.9.5 --wait
          helm install keda kedacore/keda --version 2.11.2 --wait
          helm install prometheus prometheus-community/prometheus-operator-crds --wait
          kubectl apply -f https://raw.githubusercontent.com/GlueOps/metacontroller-operator-waf/main/manifests/crd.yaml
          helm list

      - name: Checks
        env:
          CI: "true"
        run: |
          make lint
          make unittest
          make test
